### ISSUE TITLE
next level

### ISSUE THREAD

**Issue by UmarIgan** [bkitano/llama-from-scratch#3]
Hey 👋🏻,
Thanks for this amazing tutorial firstly 🙏.
I want to try this on a big corpus and use it so would you suggest this?
How can i use this model for generating next token ?  for instance my name is brian ....
and Is it possible to push trained model to huggingface hub and use it if yes how? (checked this but found nothing)

**Comment by bkitano** [comment]
hi! you definitely don't want to use this code on larger corpula; it's not optimized in the ways you need it to be.
